Purchase or Voting Intentions
test                                                                           
________________________________________

  21 respondents prefer HONDA ACCORD        

...This is  44.7 %

  12 respondents prefer MAZDA 626           

...This is  25.5 %

  10 respondents prefer FORD TEMPO          

...This is  21.3 %

   4 respondents were undecided

...This is   8.5 %

There were    0 missing cases

...This is    .0 %

Total of   47 cases
